# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vistas/hierarchy_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HierarchyDialog(object):
    def setupUi(self, HierarchyDialog):
        HierarchyDialog.setObjectName("HierarchyDialog")
        HierarchyDialog.resize(548, 499)
        HierarchyDialog.setSizeGripEnabled(True)
        self.verticalLayoutWidget = QtWidgets.QWidget(HierarchyDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 541, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_import = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_import.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_import.setStyleSheet("background-color: rgb(243,217,176)")
        self.button_import.setObjectName("button_import")
        self.horizontalLayout_3.addWidget(self.button_import)
        self.button_export = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_export.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_export.setStyleSheet("background-color: rgb(243,217,176)")
        self.button_export.setObjectName("button_export")
        self.horizontalLayout_3.addWidget(self.button_export)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.button_delete = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_delete.setStyleSheet("background-color: rgb(240,206,154)")
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout.addWidget(self.button_delete)
        self.button_add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_add.setStyleSheet("background-color: rgb(240,206,154)")
        self.button_add.setObjectName("button_add")
        self.horizontalLayout.addWidget(self.button_add)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_suppression = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_suppression.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_suppression.setStyleSheet("background-color: rgb(243,217,176)")
        self.button_suppression.setObjectName("button_suppression")
        self.horizontalLayout_2.addWidget(self.button_suppression)
        self.button_propuesta = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_propuesta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_propuesta.setStyleSheet("background-color: rgb(243,217,176)")
        self.button_propuesta.setObjectName("button_propuesta")
        self.horizontalLayout_2.addWidget(self.button_propuesta)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.button_guardar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_guardar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_guardar.setStyleSheet("background-color: rgb(223,153,44)")
        self.button_guardar.setObjectName("button_guardar")
        self.verticalLayout.addWidget(self.button_guardar)

        self.retranslateUi(HierarchyDialog)
        QtCore.QMetaObject.connectSlotsByName(HierarchyDialog)

    def retranslateUi(self, HierarchyDialog):
        _translate = QtCore.QCoreApplication.translate
        HierarchyDialog.setWindowTitle(_translate("HierarchyDialog", "Jerarquías de generalización"))
        self.button_import.setText(_translate("HierarchyDialog", "Importar jerarquía"))
        self.button_export.setText(_translate("HierarchyDialog", "Exportar jerarquía"))
        self.button_delete.setText(_translate("HierarchyDialog", "Borrar nivel"))
        self.button_add.setText(_translate("HierarchyDialog", "Añadir nivel"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("HierarchyDialog", "Nivel 0"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("HierarchyDialog", "Nivel 1"))
        self.button_suppression.setText(_translate("HierarchyDialog", "Añadir supresión"))
        self.button_propuesta.setText(_translate("HierarchyDialog", "Generar propuesta numérica"))
        self.button_guardar.setText(_translate("HierarchyDialog", "Guardar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HierarchyDialog = QtWidgets.QDialog()
    ui = Ui_HierarchyDialog()
    ui.setupUi(HierarchyDialog)
    HierarchyDialog.show()
    sys.exit(app.exec_())
